#!/usr/bin/env python
#-*- coding: utf-8 -*-

import argparse
from termcolor import colored
import matplotlib.pyplot as plt

def two_subplot(x,y,x2,y2,kind):

    fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15, 5))
    axes[0].kind(x, y)
    axes[1].kind(x2, y2)
# x = x value of dataset 1
# y = y value of dataset 1
# x2 = x value of dataset 2
# y2 = y value of dataset 2
# kind = the kind of graph it will be e.g. bar, plot, scatter etc.
